sudo : required
services:
  - docker

before_install:
  - docker build -t vamsibelagam/react-test -f ./client/Dockerfile .client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t vamsibelagam/multi-client ./client
  - docker build -t vamsibelagam/multi-nginx ./nginx
  - docker build -t vamsibelagam/multi-server ./server
  - docker build -t vamsibelagam/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vamsibelagam/multi-client
  - docker push vamsibelagam/multi-nginx
  - docker push vamsibelagam/multi-server
  - docker push vamsibelagam/multi-worker