sudo : required
services:
  - docker

before_install:
  - docker build -t vamsibelagam/react-test -f ./client/Dockerfile.dev .client

script:
  - docker run -e CI=true USERNAME/react-test npm test
  
after_success:
  - docker build -t vamsibelagam/multi-client ./client
  - docker build -t vamsibelagam/multi-nginx ./nginx
  - docker build -t vamsibelagam/multi-server ./server
  - docker build -t vamsibelagam/multi-worker ./worker




