version: "3"
services:
  client:
    image: "vamsibelagam/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "vamsibelagam/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=multi-docker-redis.w3fpo4.ng.0001.aps1.cache.amazonaws.com
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=multi-docker-postgres.cl1i2qyq7bpl.ap-south-1.rds.amazonaws.com
      - PGDATABASE=fibvalues
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
  worker:
    image: "vamsibelagam/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=multi-docker-redis.w3fpo4.ng.0001.aps1.cache.amazonaws.com
      - REDIS_PORT=6379
  nginx:
    image: "vamsibelagam/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
